export const GET_FORMS = 'GET_FORMS';
export const GET_FORMS_SUCCESS = 'GET_FORMS_SUCCESS';
export const GET_FORMS_FAILED = 'GET_FORMS_FAILED';

export const UPDATE_FORM = 'UPDATE_FORMS';
export const UPDATE_FORM_SUCCESS = 'UPDATE_FORMS_SUCCESS';
export const UPDATE_FORM_FAILED = 'UPDATE_FORMS_FAILED';

export const DELETE_FORM = 'DELETE_FORM';
export const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS';
export const DELETE_FORM_FAILED = 'DELETE_FORM_FAILED';

export const CREATE_FORM = 'CREATE_FORM';
export const CREATE_FORM_SUCCESS = 'CREATE_FORM_SUCCESS';
export const CREATE_FORM_DELETE = 'CREATE_FORM_DELETE';
